version: '3.4'

services:

  pativercore.webapi:
    image: ${DOCKER_REGISTRY-}pativercorewebapi
    container_name: pativer-core
    build:
      context: .
      dockerfile: PatiVerCore.WebApi/Dockerfile
    restart: always
    ports:
      - "5001:8080"
    depends_on:
      - redis_cache

  redis_cache:
    image: redis:7.4.0-alpine3.20
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
